[package]
name = "couscousy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sada = { path = "./sada_proc_macro/" }

actix-web = "4.0"
reqwest = "0.11"

serde_json = "1.0"