[package]
name = "couscousy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sada = { path = "./sada_proc_macro/" }
